name: nit_tools_server
description: Starting point for a Serverpod module.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod: 2.1.5
  serverpod_auth_server: 2.1.5
  collection: ^1.19.1
  googleapis_auth: ^1.6.0

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
