name: nit_tools_server
description: Starting point for a Serverpod module.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod: 2.1.5
  collection: ^1.19.1

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
