name: nit_tools_client
description: Starting point for a Serverpod module client.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  serverpod_client: 2.1.5
  serverpod_auth_client: 2.1.5
  freezed_annotation: ^2.4.4
